auth0/docs

docs/api-reference.md, docs/azure-tutorial.md, docs/ios-tutorial.md, docs/jwt.md, docs/scenarios/parse.md, docs/server-apis/php-laravel.md, docs/sso/single-page-apps-sso.md, docs/user-profile.md, docs/waad-clientid.md
Rename Windows Azure to Microsoft Azure
=> Fixed typos + rename Azure

docs/scenarios/amazon-cognito.md, docs/scenarios/index.md, settings.json
=> Added Scenarios to the left sidebar

docs/client-platforms/angularjs.md, docs/client-platforms/jquery.md, docs/client-platforms/vanillajs.md, docs/server-apis/aspnet-webapi.md, docs/server-apis/golang.md, docs/server-apis/java-spring-security.md, docs/server-apis/java.md, docs/server-apis/nodejs.md, docs/server-apis/php-laravel.md, docs/server-apis/php.md, docs/server-apis/python.md, docs/server-apis/rails.md, docs/server-apis/ruby.md, docs/server-platforms/asp-classic.md, docs/server-platforms/golang.md, docs/server-platforms/java.md, docs/server-platforms/nancyfx.md, docs/server-platforms/nodejs.md, docs/server-platforms/php.md, docs/server-platforms/python.md, docs/server-platforms/rails.md, docs/server-platforms/scala.md
Added notes and edits based on customer feedback.
=> Edits on PHP and other tutorials

docs/connector/high-availability.md, docs/connector/install-other-platforms.md, docs/connector/install.md, docs/connector/prerequisites.md, docs/connector/scom-monitoring.md, docs/connector/troubleshooting.md, docs/connector/update.md
Normalized terminology. Fixed typos, added info to Connector section.
=> Edits to Connector section

docs/aws.md
Fixed link to AWS. Added comment on AWS roles.
=> Added more info on AWS integration

docs/auth0js.md, docs/exact-clientid.md, docs/har.md, settings.json
Edits to HAR, Exact IdP connection + auth0.js
=> Edits to HAR, Exact IdP connection + auth0.js

docs/auth0js.md
=> Fixed code blocks

npm-shrinkwrap.json, package.json
=> Revert "Added Android tutorial to quickstart"

docs/lock.md, docs/login-widget.md, docs/login-widget2.md, lib/extensions.js, lib/sdk-snippets/login-widget/index.jade, themes/default/public/css/docs.css, themes/default/public/css/docs.styl
* Fixed login widget links
* Added new deprecation notice to old widget pages
* Added showdown markdown extension for blockquotes warnings + styles
=> Old login widget deprecations

app.js
Forgot to add this line to my last PR, this enabled the warning block markdown extension.
=> Added warning block extension

docs/connector/considerations-non-ad.md, docs/ssocircle.md
Edits to AD Connector and SSOCircle tutorial
=> Edits to AD Connector and SSOCircle tutorial

docs/appliance.md, docs/samlsso-auth0-to-auth0.md, docs/test-partner-connection.md
* Fixed broken link
* Minor edits on SAML-SAML doc
* New Testing tutorial for Enterprise connections
=> Edits and new testing tutorial

docs/applications.md, settings.json
This covers what we have today: "Applications / APIs". In the future we will need to update this document to be in line with the new and improved naming (API keys, client IDs, stamps, ...)
=> Added "What is an application"

docs/scenarios/ionic-and-firebase.md
=> Various edits to the tutorial 

docs/oauth2.md
New doc on adding generic OAuth2 servers in Auth0
=> New doc on adding generic OAuth2 servers in Auth0

docs/scenarios/amazon-cognito.md
Regarding this issue: https://forums.aws.amazon.com/thread.jspa?messageID=602238&#602238
=> Update Amazon Cognito RS256

npm-shrinkwrap.json, package.json
=> Shrinkwrap issues

docs/oauth2-examples.md, docs/overview.md
Added sample OAuth2 connections + Overview
=> Added sample OAuth2 connections + Overview

docs/server-platforms/rails.md
Moved the web app quickstart to the omniauth repo.
=> Ruby quickstart now points to omniauth repo

docs/hrd.md
Fix HRD Lock customization when multiple Locks are on the page (eg: embedded Lock + popup). Icon is now only being added to the current Lock.
=> Update HRD customization

docs/connector/prerequisites.md, docs/connector/troubleshooting.md, docs/overview.md, lib/redirects/redirect-urls.json
Minor edits, Added PROXY for Connector, changed diagram on overview
=> Minor edits, Added PROXY for Connector, changed diagram on overview

docs/oauth1.md, docs/oauth2-examples.md, docs/oauth2.md
Added OAuth1 generic connetion and XING sample
=> Added OAuth1 generic connetion and XING sample

docs/angular-tutorial.md
It was 'auth' instead of 'auth0'
=> fixing typo in angular module dependency.

docs/oauth2-examples.md
Added DigitalOcean as an OAuth2 connection
=> Added DigitalOcean as an OAuth2 connection

docs/oauth2-examples.md
=> Added imgur as an example

docs/appliance/clock.md, docs/ssocircle.md
Added explanation for how to get ssocircle IDP metadata, made images look better
=> Added explanation for how to get ssocircle IDP metadata, made images look better

deployment.md
Added notes and matrix for 4 deployment models.
=> Added notes on deployment models

docs/okta.md
Added two troubleshooting tips to Okta configuration instructions
=> Add troubleshooting tips to Okta configuration instructions

docs/logout.md
=> Replace logout with v2/logout

docs/saml-apps.md
Added master list of SAML apps Auth0 supports and their config
=> Added master list of SAML apps Auth0 supports and their config

.jshintrc, app.js, lib/authorizations.js, lib/clients.js, lib/env.js, lib/regions.js, lib/sdk-snippets/lock/demos-routes.js, lib/sdk-snippets/lock/snippets-routes.js, lib/sdk-snippets/lock/snippets/embedded.html, lib/sdk-snippets/lock/snippets/login.html, lib/sdk-snippets/lock/widget_script_url.js, lib/sdk-snippets/login-widget/demos-routes.js, lib/sdk-snippets/login-widget/middleware.js, lib/sdk-snippets/login-widget/widget_script_url.js, lib/sdk-snippets/login-widget2/demos-routes.js, lib/sdk-snippets/login-widget2/widget_script_url.js, lib/set_current_tenant.js, lib/set_user_is_owner.js, package.json, themes/default/views/base.jade
Manage should be merged first:
https://github.com/auth0/manage/pull/475
=> Implement multiregion support

docs/saml-configuration.md
Added links to a couple other new SAML doc pages into this page, so it can serve as one-stop shopping for SAML info.
=> clarify text, add links to new SAML docs

docs/saml-configuration.md
Removed the word "button" from the text.
=> remove the word button from the text
